name: saltstack-zsh-formula
source: https://github.com/bechtoldt/saltstack-zsh-formula
summary: SaltStack Formula to set up and configure zsh, a shell designed for interactive use
todo:
  - add instructions how to use formhelper, add information about it in the formula-docs (dependency), show up alternative?
  - 'table/ matrix: os/salt compatibility (dedicated file)'
  - add list of available states
  - add tests
